### ISSUE TITLE
The plugin is not available via Package Control management

### ISSUE THREAD

**Issue by delphym** [june07/sublime-Jenkinsfile#1]
Trying to install it using the easier and preferred way with _Package Control_.

However when I open “Package Control: Install Package” command, type "Jenkinsfile" nothing is available to install with such name. 

Using Sublime 3.2.1 #3207 on Win10 and Ubuntu Trusty

**Comment by june07** [comment]
Looks like it was just (finally) committed 4 days ago!
https://github.com/wbond/package_control_channel/pull/7483
